version: 2
project_name: dot

# 输出目录（默认 dist）
dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: dot
    main: ./cmd/server
    binary: dot
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X dotmostbox/internal/update.Version={{ .Version }}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binaries
    ids:
      - dot
    formats: ["binary"]
    # go-selfupdate 必须按默认命名习惯输出文件名
    name_template: >-
      {{ .Binary }}-{{ .Os }}-{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# 解决重复上传同名资产导致的 422 错误
release:
  replace_existing_artifacts: true

# 使用 UPX 压缩（macOS Ventura 暂不支持，过滤 macOS）
upx:
  - enabled: true
    ids: [dot]
    goos: [linux, windows]
    compress: best
    lzma: true
    brute: false

dockers:
  - ids: [dot]
    goos: linux
    goarch: amd64
    image_templates:
      - docker.io/mostpeople/dot:{{ .Version }}-amd64
      - docker.io/mostpeople/dot:latest-amd64
    dockerfile: ../Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --build-arg=BINARY=dot-linux-amd64
  - ids: [dot]
    goos: linux
    goarch: arm64
    image_templates:
      - docker.io/mostpeople/dot:{{ .Version }}-arm64
      - docker.io/mostpeople/dot:latest-arm64
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --build-arg=BINARY=dot-linux-arm64

docker_manifests:
  - name_template: docker.io/mostpeople/dot:{{ .Version }}
    image_templates:
      - docker.io/mostpeople/dot:{{ .Version }}-amd64
      - docker.io/mostpeople/dot:{{ .Version }}-arm64
  - name_template: docker.io/mostpeople/dot:latest
    image_templates:
      - docker.io/mostpeople/dot:latest-amd64
      - docker.io/mostpeople/dot:latest-arm64
